stages:
  - build
  - deploy

default:
  image: golang:tip-alpine

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == "main"

build:
  stage: build
  before_script:
    - go get .
  script:
    - go build -o apiserver
    - chmod a+x apiserver
  artifacts:
    paths:
      - apiserver

scp_binary:
  stage: deploy
  before_script:
    - apk add --no-cache openssh coreutils
    - eval $(ssh-agent -s)
    - echo "$SSH_DEPLOY_PRIVATE_KEY_B64" | base64 -d | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
  script:
    - scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null
        apiserver $SSH_DEPLOY_USERNAME@$SSH_DEPLOY_HOST:/home/$SSH_DEPLOY_USERNAME/apiserver
